name: amlenv
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.9.13
  - keras=2.6.0
  - keras-gpu=2.6.0
  - matplotlib=3.5.2
  - matplotlib-inline=0.1.6
  - numpy=1.23.4
  - pandas=1.4.4
  - scikit-learn=1.0.2
  - spyder
  - seaborn=0.12.0
  - pyts=0.12.0
